/* @macrome
 * @generated-from ./$concat.test.js
 * @generated-by generate/generators/$tests/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncConcat, asyncToArray, range } from '../../..';

describe('asyncConcat', () => {
  it('concats iterables', async () => {
    const iter = asyncConcat(
      range({
        start: 1,
        end: 3,
      }),
      [3, 4],
    );
    expect(await asyncToArray(iter)).toEqual([1, 2, 3, 4]);
  });
});
