/* @macrome
 * @generated-from ./$append.test.js
 * @generated-by generate/generators/$tests/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { append, toArray, wrap } from '../../..';

describe('append', () => {
  it('appends a value', () => {
    expect(toArray(append(3, wrap([1, 2])))).toEqual([1, 2, 3]);
  });
});
