/**
 * @generated-from ./async-append.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncAppend, asyncToArray, asyncWrap } from '../../..';
describe('asyncAppend', () => {
  it('appends a value', async () => {
    expect(await asyncToArray(asyncAppend(3, asyncWrap([1, 2])))).toEqual([1, 2, 3]);
  });
});
