/**
 * @generated-from ./$select-by.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';
import { __peekerate } from '../$peekerate/peekerate.js';

export function __selectBy(iterable, selector, mapper) {
  const peekr = __peekerate(iterable);

  if (!peekr.done) {
    let bestItem = peekr.value;
    let bestValue = mapper(bestItem);

    peekr.advance();
    while (!peekr.done) {
      const candidate = peekr.value;
      const candidateValue = mapper(candidate);
      if (selector(bestValue, candidateValue)) {
        bestItem = candidate;
        bestValue = candidateValue;
      }
      peekr.advance();
    }
    return bestItem;
  }
}

export const selectBy = iterableCurry(__selectBy, {
  reduces: true,
});
