/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$map.js#1643907550751
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { iterableCurry } from '../../internal/iterable.js';

export function* __map(source, func) {
  let c = 0;
  for (const value of source) {
    yield func(value, c++);
  }
}

export const map = /*#__PURE__*/ iterableCurry(__map);
