/* @macrome
 * @generated-from ./$flat.js
 * @generated-by generate/generators/$methods/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncIterableCurry, asyncIsIterable } from '../../internal/async-iterable';

const defaultShouldFlat = item => typeof item !== 'string' && asyncIsIterable(item);

async function* asyncFlatInternal(shouldFlat, depth, currentDepth, source) {
  for await (const item of source) {
    if (currentDepth < depth && (await shouldFlat(item))) {
      yield* asyncFlatInternal(shouldFlat, depth, currentDepth + 1, item);
    } else {
      yield item;
    }
  }
}

export function asyncFlat(source, shouldFlat = defaultShouldFlat, depthOrOptions = 1) {
  let depth = depthOrOptions;
  if (depthOrOptions && typeof depthOrOptions === 'object') {
    ({ shouldFlat = defaultShouldFlat, depth = 1 } = depthOrOptions);
  }

  return asyncFlatInternal(shouldFlat, depth, 0, source);
}

export default asyncIterableCurry(asyncFlat, {
  minArgs: 0,
  maxArgs: 2,
});
