/**
 * @generated-from ./$flat.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable';

const defaultShouldFlat = item =>
  typeof item[Symbol.iterator] === 'function' && typeof item !== 'string';

function* flatInternal(shouldFlat, depth, currentDepth, iterable) {
  for (const item of iterable) {
    if (currentDepth < depth && shouldFlat(item)) {
      yield* flatInternal(shouldFlat, depth, currentDepth + 1, item);
    } else {
      yield item;
    }
  }
}

function flat(shouldFlat = defaultShouldFlat, depthOrOptions = 1, iterable) {
  let depth = depthOrOptions;

  if (depthOrOptions && typeof depthOrOptions === 'object') {
    ({ shouldFlat = defaultShouldFlat, depth = 1 } = depthOrOptions);
  }

  return flatInternal(shouldFlat, depth, 0, iterable);
}

export default iterableCurry(flat, {
  minArgs: 0,
  maxArgs: 2,
});
