/**
 * @generated-from ./$size.spec.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import assert from 'static-type-assert';
import { asyncSize } from 'iter-tools-es';

declare const Ø: never;

assert<Promise<4>>(asyncSize(Ø as [0, 1, 2, 3]));
assert<Promise<0 | 1 | 2>>(asyncSize(Ø as [] | [number] | [number, number]));
assert<Promise<number>>(asyncSize(Ø as Array<number>));
assert<Promise<number>>(asyncSize(Ø as string));
