/**
 * @generated-from ./$size.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { size } from '@iter-tools/es';
import { wrap } from '../../../test/helpers.js';

describe('size', () => {
  describe('when iterable is empty', () => {
    it('returns 0', () => {
      expect(size(null)).toBe(0);
      expect(size(undefined)).toBe(0);
      expect(size(wrap([]))).toBe(0);
    });
  });

  describe('when iterable contains values', () => {
    it('return number of items in iterable', () => {
      expect(size(wrap([1, 2, 3, 4, 5, 6]))).toBe(6);
    });
  });
});
