/**
 * @generated-from ./$min-by.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { __asyncPeekerate } from '../$peekerate/async-peekerate.js';
import { asyncIterableCurry } from '../../internal/async-iterable.js';
import { defaultCompareOrder } from '../../internal/compare.js';

export async function __asyncMinBy(iterable, mapper, compare = defaultCompareOrder) {
  const peekr = await __asyncPeekerate(iterable);

  if (!peekr.done) {
    let minValue = peekr.value;
    let minMappedValue = await mapper(minValue);

    await peekr.advance();
    while (!peekr.done) {
      const value = peekr.value;
      const mappedValue = await mapper(value);
      if (compare(minMappedValue, mappedValue) > 0) {
        minValue = value;
        minMappedValue = mappedValue;
      }
      await peekr.advance();
    }
    return minValue;
  }
}

export const asyncMinBy = asyncIterableCurry(__asyncMinBy, {
  reduces: true,
  minArgs: 1,
  maxArgs: 2,
  growRight: true,
});
