/**
 * @generated-from ./../impls/array-from-async/array-from-async.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { arrayFromAsync as default } from '../impls/array-from-async/array-from-async';
