/**
 * @generated-from ./../impls/$round-robin/async-round-robin.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { asyncRoundRobin as default } from '../impls/$round-robin/async-round-robin';
