/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$split/async-split.d.ts#1643837503098
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { asyncSplit as default } from '../impls/$split/async-split';
