/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$first/async-first.js#1643837503064
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { asyncFirst as default } from '../impls/$first/async-first.js';
