/**
 * @generated-from ./../impls/$prepend/async-prepend.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { asyncPrepend as default } from '../impls/$prepend/async-prepend.js';
