/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$interpose-seq/async-interpose-seq.d.ts#1643837503076
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { asyncInterposeSeq as default } from '../impls/$interpose-seq/async-interpose-seq';
