/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$interpose/async-interpose.d.ts#1643837503077
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { asyncInterpose as default } from '../impls/$interpose/async-interpose';
