/**
 * @generated-from ./../impls/$select-by/async-select-by.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { asyncSelectBy as default } from '../impls/$select-by/async-select-by';
