/**
 * @generated-from ./../impls/$min-by/async-min-by.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { asyncMinBy as default } from '../impls/$min-by/async-min-by';
