/**
 * @generated-from ./../impls/exec-pipe/exec-pipe.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { execPipe as default } from '../impls/exec-pipe/exec-pipe';
