/**
 * @generated-from ./../impls/first-lowest/first-lowest.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { firstLowest as default } from '../impls/first-lowest/first-lowest';
