/**
 * @generated-from ./../impls/$flat-map/flat-map.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { default } from '../impls/$flat-map/flat-map.js';
