/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/is-async-iterable/is-async-iterable.d.ts#1643837503127
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { isAsyncIterable as default } from '../impls/is-async-iterable/is-async-iterable';
