/**
 * @generated-from ./../impls/repeat-times/repeat-times.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { repeatTimes as default } from '../impls/repeat-times/repeat-times.js';
