/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/repeat-times/repeat-times.d.ts#1643837503140
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { repeatTimes as default } from '../impls/repeat-times/repeat-times';
