/**
 * @generated-from ./../impls/$reverse/reverse.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

export { reverse as default } from '../impls/$reverse/reverse';
