/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$spliterate/spliterate.js#1643837503100
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { spliterate as default } from '../impls/$spliterate/spliterate.js';
