/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$starts-with-seq/starts-with-seq.d.ts#1643837503104
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { startsWithSeq as default } from '../impls/$starts-with-seq/starts-with-seq';
