/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$window-ahead/window-ahead.d.ts#1643837503115
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { windowAhead as default } from '../impls/$window-ahead/window-ahead';
