/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$filter.d.ts#1643837503059
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function filter<T, S extends T>(
  predicate: (value: T, i: number) => value is S,
): (source: Wrappable<T>) => IterableIterator<S>;

declare function filter<T>(
  predicate: (value: T, i: number) => boolean,
): (source: Wrappable<T>) => IterableIterator<T>;

declare function filter<T, S extends T>(
  predicate: (value: T, i: number) => value is S,
  source: Wrappable<T>,
): IterableIterator<S>;

declare function filter<T>(
  predicate: (value: T, i: number) => boolean,
  source: Wrappable<T>,
): IterableIterator<T>;

export { filter };
