/* @macrome
 * @generated-from ./$to-object.d.ts
 * @generated-by generate/generators/$types/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable } from '../../types/async-iterable';

declare function asyncToObject<V>(
  source: AsyncSourceIterable<[string, V]>,
):
  | {
      [key: string]: V;
    }
  | Promise<{
      [key: string]: V;
    }>;

export default asyncToObject;
