/**
 * @generated-from ./$to-object.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable } from '../../types/async-iterable';
declare function asyncToObject<V>(
  source: AsyncSourceIterable<[string, V]>,
):
  | {
      [key: string]: V;
    }
  | Promise<{
      [key: string]: V;
    }>;
export default asyncToObject;
