/* @macrome
 * @generated-from ./$to-object.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { SourceIterable } from '../../types/iterable';

declare function toObject<V>(
  source: SourceIterable<[string, V]>,
): {
  [key: string]: V;
};

export default toObject;
