/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$starts-with-seq.test.ts#1643907550769
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { startsWithSeq } from 'iter-tools-es';
import { wrap } from '../../../test/helpers.js';

describe('startsWithSeq', () => {
  describe('when iterable starts with the sequence', () => {
    it('returns true', () => {
      expect(startsWithSeq(wrap([1, 2]), wrap([1, 2, 3]))).toBe(true);
    });
  });

  describe('when iterable is equal to the sequence', () => {
    it('returns true', () => {
      expect(startsWithSeq(wrap([1, 2, 3]), wrap([1, 2, 3]))).toBe(true);
    });
  });

  describe('when iterable is shorter than the sequence', () => {
    it('returns false', () => {
      expect(startsWithSeq(wrap([1, 2, 3]), wrap([1, 2]))).toBe(false);
    });
  });

  describe('when iterable includes but does not start with the sequence', () => {
    it('returns false', () => {
      expect(startsWithSeq(wrap([2, 3]), wrap([1, 2, 3]))).toBe(false);
    });
  });

  describe('when iterable is empty', () => {
    describe('and the sequence is empty', () => {
      it('returns true', () => {
        expect(startsWithSeq(wrap([]), wrap([]))).toBe(true);
      });
    });

    describe('and the sequence is not empty', () => {
      it('returns false', () => {
        expect(startsWithSeq(wrap([undefined]), wrap([]))).toBe(false);
      });
    });
  });

  describe('when same function is specified', () => {
    const same = (a: number, b: number) => Math.abs(a) === Math.abs(b);
    it('uses same value to do comparison', () => {
      expect(startsWithSeq(same, wrap([-1]), wrap([1, 2, 3]))).toBe(true);
      expect(startsWithSeq(() => false, wrap([1]), wrap([1, 2, 3]))).toBe(false);
    });
  });
});
