/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$slice.d.ts#1643907550757
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function slice<T>(opts: {
  readonly start?: number;
  readonly end?: number;
  readonly step?: number;
}): (source: Wrappable<T>) => IterableIterator<T>;

declare function slice<T>(
  start?: number,
  end?: number,
  step?: number,
): (source: Wrappable<T>) => IterableIterator<T>;

declare function slice<T>(
  opts: {
    readonly start?: number;
    readonly end?: number;
    readonly step?: number;
  },
  source: Wrappable<T>,
): IterableIterator<T>;

declare function slice<T>(start: number, source: Wrappable<T>): IterableIterator<T>;

declare function slice<T>(start: number, end: number, source: Wrappable<T>): IterableIterator<T>;

declare function slice<T>(
  start: number,
  end: number,
  step: number,
  source: Wrappable<T>,
): IterableIterator<T>;

export { slice };
