/**
 * @generated-from ./$split-on.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncInputIterable, AsyncGeneratorIterator } from "../../internal/async-iterable"; // prettier-ignore

declare function asyncSplit(value: String): (iterable: String) => AsyncGeneratorIterator<String>;
declare function asyncSplit(value: any): <T = any>(iterable: AsyncInputIterable<T>) => AsyncGeneratorIterator<AsyncGeneratorIterator<T>>; // prettier-ignore

declare function asyncSplit(value: String, iterable: String): AsyncGeneratorIterator<String>;
declare function asyncSplit<T = any>(
  value: any,
  iterable: AsyncInputIterable<T>,
): AsyncGeneratorIterator<AsyncGeneratorIterator<T>>;
export default asyncSplit;
