/**
 * @generated-from ./$split-on.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable, AsyncResultIterable } from "../../types/async-iterable"; // prettier-ignore

declare function asyncSplit(value: string): (source: string) => AsyncResultIterable<string>;
declare function asyncSplit(value: any): <T = any>(source: AsyncSourceIterable<T>) => AsyncResultIterable<AsyncResultIterable<T>>; // prettier-ignore

declare function asyncSplit(value: string, source: string): AsyncResultIterable<string>;
declare function asyncSplit<T = any>(
  value: any,
  source: AsyncSourceIterable<T>,
): AsyncResultIterable<AsyncResultIterable<T>>;
export default asyncSplit;
