/**
 * @generated-from ./$split-on.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { InputIterable, GeneratorIterator } from "../../internal/iterable"; // prettier-ignore

declare function split(value: String): (iterable: String) => GeneratorIterator<String>;
declare function split(value: any): <T = any>(iterable: InputIterable<T>) => GeneratorIterator<GeneratorIterator<T>>; // prettier-ignore

declare function split(value: String, iterable: String): GeneratorIterator<String>;
declare function split<T = any>(
  value: any,
  iterable: InputIterable<T>,
): GeneratorIterator<GeneratorIterator<T>>;
export default split;
