/* @macrome
 * @generated-from ./$append.d.ts
 * @generated-by generate/generators/$types/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { SourceIterable, ResultIterable } from '../../types/iterable';

declare function append<T, V>(value: V, source: SourceIterable<T>): ResultIterable<V | T>;

declare function append<V>(value: V): <T>(source: SourceIterable<T>) => ResultIterable<V | T>;

export default append;
