/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$zip.d.ts#1643907550789
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncZip<T, U>(
  source1: AsyncWrappable<T>,
  source2: AsyncWrappable<U>,
): AsyncIterableIterator<[T, U]>;
declare function asyncZip<T, U, V>(
  source1: AsyncWrappable<T>,
  source2: AsyncWrappable<U>,
  source3: AsyncWrappable<V>,
): AsyncIterableIterator<[T, U, V]>;
declare function asyncZip<T>(...sources: Array<AsyncWrappable<T>>): AsyncIterableIterator<T[]>;

export { asyncZip };
