/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$spliterate-grouped.js#1643907550765
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { iterableCurry } from '../../internal/iterable.js';
import { GroupsIterator } from '../../internal/groups-iterator.js';
import { __map } from '../$map/map.js';
import { __wrap } from '../$wrap/wrap.js';

export function __spliterateGrouped(source, strategy, options = {}) {
  return new GroupsIterator(source, strategy, options);
}

export const spliterateGrouped = /*#__PURE__*/ iterableCurry(
  function $spliterateGrouped(...args) {
    return __map(__spliterateGrouped(...args), __wrap);
  },
  {
    minArgs: 1,
    maxArgs: 2,
    growRight: true,
  },
);
