/**
 * @generated-from ./$is-sorted.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';
import { defaultCompare } from '../../internal/compare.js';
import { peekerate } from '../$peekerate/peekerate.js';

export function isSorted(iterable, comparator = defaultCompare) {
  const peekr = peekerate(iterable);

  while (!peekr.done) {
    const { value } = peekr;
    peekr.advance();

    if (!peekr.done && comparator(value, peekr.value) > 0) {
      peekr.return();
      return false;
    }
  }
  return true;
}

export default /*#__PURE__*/ iterableCurry(isSorted, {
  reduces: true,
  minArgs: 0,
  maxArgs: 1,
});
