/**
 * @generated-from ./$starts-with.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';
import { __firstOr } from '../$first-or/first-or.js';

const none = Symbol('none');

export function __startsWith(iterable, value, same = Object.is) {
  const first = __firstOr(iterable, none);
  if (first === none) return false;
  return same(value, first);
}

export const startsWith = /*#__PURE__*/ iterableCurry(__startsWith, {
  minArgs: 1,
  maxArgs: 2,
  reduces: true,
  validateArgs(args) {
    if (true && typeof args[0] === 'string') {
      console.warn('For string inputs use startsWithSeq instead of startsWith');
    }
  },
});
