/* @macrome
 * @generated-from ./$for-each.test.js
 * @generated-by generate/generators/$tests/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { forEach } from '../../..';

describe('forEach', () => {
  it('iterates over an iterable', () => {
    const arr: Array<number> = [];
    forEach(item => arr.push(item), [1, 2, 3]);
    expect(arr).toEqual([1, 2, 3]);
  });

  it('iterates over an iterable using a promise', () => {
    const arr: Array<number> = [];
    forEach(
      item => {
        arr.push(item);
        return Promise.resolve(0);
      },
      [1, 2, 3],
    );
    expect(arr).toEqual([1, 2, 3]);
  });

  it('iterates over an iterable (curried)', () => {
    const arr: Array<number> = [];
    const forEachPush = forEach((item: number) => arr.push(item));
    forEachPush([1, 2, 3]);
    expect(arr).toEqual([1, 2, 3]);
  });
});
