/* @macrome
 * @generated-from ./async-drop.test.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncDrop, asyncToArray, asyncWrap } from '../../..';

describe('asyncDrop', () => {
  it('drops n items', async () => {
    expect(await asyncToArray(asyncDrop(1, asyncWrap([1, 2, 3])))).toEqual([2, 3]);
  });
});
