/**
 * @generated-from ./$drop.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

/* eslint-disable no-unused-vars,import/no-duplicates,no-constant-condition */

import { drop, toArray, wrap } from '../../..';
describe('drop', () => {
  it('drops n items', () => {
    expect(toArray(drop(1, wrap([1, 2, 3])))).toEqual([2, 3]);
  });
});
