/**
 * @generated-from ./$flat-map.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncInputIterable, AsyncGeneratorIterator } from '../../internal/async-iterable';
declare function asyncFlatMap<O, T = any>(
  func: (item: T) => AsyncInputIterable<O> | Promise<AsyncInputIterable<O>>,
): (iter: AsyncInputIterable<T>) => AsyncGeneratorIterator<O>;
declare function asyncFlatMap<O, T = any>(
  func: (item: T) => AsyncInputIterable<O> | Promise<AsyncInputIterable<O>>,
  iter: AsyncInputIterable<T>,
): AsyncGeneratorIterator<O>;
export default asyncFlatMap;
