/**
 * @generated-from ./$flat-map.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { SourceIterable, ResultIterable } from '../../types/iterable';
declare function flatMap<O, T = any>(
  func: (item: T) => SourceIterable<O>,
): (iter: SourceIterable<T>) => ResultIterable<O>;
declare function flatMap<O, T = any>(
  func: (item: T) => SourceIterable<O>,
  iter: SourceIterable<T>,
): ResultIterable<O>;
export default flatMap;
