/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$prepend.d.ts#1643837503084
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function prepend<T, V>(value: V, source: Wrappable<T>): IterableIterator<V | T>;

declare function prepend<V>(value: V): <T>(source: Wrappable<T>) => IterableIterator<V | T>;

export { prepend };
