/**
 * @generated-from ./$slice.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';
declare function asyncSlice<T = any>(opts: {
  readonly start?: number;
  readonly end?: number;
  readonly step?: number;
}): (iterable: AsyncSourceIterable<T>) => AsyncResultIterable<T>;
declare function asyncSlice<T = any>(
  start?: number,
  end?: number,
  step?: number,
): (iterable: AsyncSourceIterable<T>) => AsyncResultIterable<T>;
declare function asyncSlice<T = any>(
  opts: {
    readonly start?: number;
    readonly end?: number;
    readonly step?: number;
  },
  iterable: AsyncSourceIterable<T>,
): AsyncResultIterable<T>;
declare function asyncSlice<T = any>(
  start: number,
  iterable: AsyncSourceIterable<T>,
): AsyncResultIterable<T>;
declare function asyncSlice<T = any>(
  start: number,
  end: number,
  iterable: AsyncSourceIterable<T>,
): AsyncResultIterable<T>;
declare function asyncSlice<T = any>(
  start: number,
  end: number,
  step: number,
  iterable: AsyncSourceIterable<T>,
): AsyncResultIterable<T>;
export default asyncSlice;
