/* @macrome
 * @generated-from ./$round-robin.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';

// prettier-ignore
declare function asyncRoundRobin<T>(...sources: Array<AsyncSourceIterable<T>>): AsyncResultIterable<T>

declare function asyncRoundRobin<T>(
  step: number,
  ...sources: Array<AsyncSourceIterable<T>>
): AsyncResultIterable<T>;

declare function asyncRoundRobin<T>(
  start: number,
  step: number,
  ...sources: Array<AsyncSourceIterable<T>>
): AsyncResultIterable<T>;

declare function asyncRoundRobin<T>(
  options: {
    start?: number;
    step?: number;
  },
  ...sources: Array<AsyncSourceIterable<T>>
): AsyncResultIterable<T>;

declare function asyncRoundRobin(
  step: number,
): <T>(...sources: Array<AsyncSourceIterable<T>>) => AsyncResultIterable<T>;

declare function asyncRoundRobin(
  start: number,
  step: number,
): <T>(...sources: Array<AsyncSourceIterable<T>>) => AsyncResultIterable<T>;

declare function asyncRoundRobin(options: {
  start?: number;
  step?: number;
}): <T>(...sources: Array<AsyncSourceIterable<T>>) => AsyncResultIterable<T>;

export default asyncRoundRobin;
