/**
 * @generated-from ./array-last-or.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { arrayLastOr } from '../../..';
describe('arrayLastOr', () => {
  describe('when there is no array', () => {
    it('returns undefined', () => {
      expect(arrayLastOr(null)).toBe(null);
    });
  });
  describe('when the array is empty', () => {
    it('returns undefined', () => {
      expect(arrayLastOr(null, [])).toBe(null);
    });
  });
  describe('when the array is not empty', () => {
    it('returns the last value', () => {
      expect(arrayLastOr(null, [1, 2, 3])).toBe(3);
    });
  });
});
