/**
 * @generated-from ./$join-with-seq.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import {
  SourceIterable as SyncSourceIterable,
  SourceIterable,
  ResultIterable,
} from '../../types/iterable';

declare function joinWithSeq<W, T>(
  seq: SyncSourceIterable<W>,
  source: SourceIterable<SourceIterable<T>>,
): ResultIterable<T | W>;

declare function joinWithSeq<W>(
  seq: SyncSourceIterable<W>,
): <T>(source: SourceIterable<SourceIterable<T>>) => ResultIterable<T | W>;

export { joinWithSeq };
