/**
 * @generated-from ./$multi-partition.spec.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import assert from 'static-type-assert';
import { AsyncIterable, AsyncIterableIterator, AsyncPromise } from '../internal/async-iterable';
import { asyncMultiPartition } from '..';
declare var Ø: never;
assert<IterableIterator<AsyncIterableIterator<number>>>(
  asyncMultiPartition(Ø as (x: number) => AsyncPromise<number>, Ø as AsyncIterable<number>),
);
assert<IterableIterator<AsyncIterableIterator<number>>>(
  asyncMultiPartition(Ø as (x: number) => AsyncPromise<number>)(Ø as AsyncIterable<number>),
);
