/**
 * @generated-from ./$join-with.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncInputIterable, AsyncGeneratorIterator } from '../../internal/async-iterable';
declare function asyncJoinWith<W, T = any>(
  value: W,
  iterable: AsyncInputIterable<AsyncInputIterable<T>>,
): AsyncGeneratorIterator<T | W>;
declare function asyncJoinWith<W>(
  value: W,
): <T = any>(iterable: AsyncInputIterable<AsyncInputIterable<T>>) => AsyncGeneratorIterator<T | W>;
export default asyncJoinWith;
