/* @macrome
 * @generated-from ./$join-with.d.ts
 * @generated-by generate/generators/$types/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';

declare function asyncJoinWith<W, T>(
  separator: W,
  source: AsyncSourceIterable<AsyncSourceIterable<T>>,
): AsyncResultIterable<T | W>;

declare function asyncJoinWith<W>(
  separator: W,
): <T>(source: AsyncSourceIterable<AsyncSourceIterable<T>>) => AsyncResultIterable<T | W>;

export default asyncJoinWith;
