/**
 * @generated-from ./$join-with.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable';
import { joinWithSeq } from '../$join-with-seq/join-with-seq';

export function joinWith(source, separator) {
  return joinWithSeq(source, [separator]);
}

export default iterableCurry(joinWith, {
  validateArgs(args) {
    if (true && typeof args[1] === 'string') {
      console.warn(`For string inputs use joinWithSeq instead of joinWith`);
    }
  },
});
