/**
 * @generated-from ./split-with.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { unwrapDeep as uw } from '../../../__tests__/helpers';
import { splitWith } from '../../..';
describe('splitWith', () => {
  it('should split between every item which is equal to the on argument', () => {
    expect(uw(splitWith(i => i === null, [1, null, 2, null, 3]))).toEqual([[1], [2], [3]]);
  });
  describe('given a string', () => {
    it('should split on every character which matches the accessor', () => {
      expect(uw(splitWith(i => i === 'Ø', '11Ø22Ø33'))).toEqual(['11', '22', '33']);
    });
    it('should split on a regex', () => {
      expect(uw(splitWith(/Ø/, '11Ø22Ø33'))).toEqual(['11', '22', '33']);
    });
  });
});
