/**
 * @generated-from ./$fork.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { IterableIterator as SyncIterableIterator } from '../../types/iterable';
import { AsyncWrappable, AsyncSingletonIterableIterator } from '../../types/async-iterable';

declare function asyncFork<T>(
  source: AsyncWrappable<T>,
): SyncIterableIterator<AsyncSingletonIterableIterator<T>>;

export { asyncFork };
