/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$to-array.test.ts#1643907550780
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncToArray } from 'iter-tools-es';
import { asyncWrap } from '../../../test/async-helpers.js';

describe('asyncToArray', () => {
  it('turns an iterable into an array', async () => {
    expect(await asyncToArray(asyncWrap([1, 2, 3]))).toEqual([1, 2, 3]);
  });
});
