/* @macrome
 * @generated-from ./$for-each.d.ts
 * @generated-by generate/generators/$types/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable } from '../../types/async-iterable';

declare function asyncForEach<T>(
  callback: (item: T, i: number) => void,
): (iterable: AsyncSourceIterable<T>) => Promise<void>;

declare function asyncForEach<T>(
  callback: (item: T, i: number) => void,
  iterable: AsyncSourceIterable<T>,
): Promise<void>;

export default asyncForEach;
