/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$every.test.ts#1643837503058
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { every } from 'iter-tools-es';
import { wrap } from '../../../test/helpers.js';

describe('every', () => {
  describe('when iterable is empty', () => {
    it('returns true', () => {
      expect(every(() => true, null)).toEqual(true);
      expect(every(() => true, undefined)).toEqual(true);
      expect(every(() => true, wrap([]))).toEqual(true);
    });
  });

  describe('when no values match predicate', () => {
    it('returns false', () => {
      expect(every((val) => val !== val, [1, 2, 3])).toBe(false);
    });
  });

  describe('when some values match predicate', () => {
    it('returns false', () => {
      expect(every((val) => val > 2, [1, 2, 3])).toBe(false);
    });
  });

  describe('when every value matches predicate', () => {
    it('returns true', () => {
      expect(every((val) => val > 0, [1, 2, 3])).toBe(true);
    });
  });
});
