/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$wrap.test.ts#1643907550786
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncWrap } from 'iter-tools-es';
import { asyncWrap as asyncTestWrap, asyncUnwrap } from '../../../test/async-helpers.js';

describe('asyncWrap', () => {
  describe('when source is empty', () => {
    it('yields no values', async () => {
      expect(await asyncUnwrap(asyncWrap(undefined))).toEqual([]);
      expect(await asyncUnwrap(asyncWrap(null))).toEqual([]);
      expect(await asyncUnwrap(asyncWrap(asyncTestWrap([])))).toEqual([]);
    });
  });

  describe('when source has values', () => {
    it('yields the values from source', async () => {
      expect(await asyncUnwrap(asyncWrap([1, 2, 3]))).toEqual([1, 2, 3]);
      expect(await asyncUnwrap(asyncWrap(asyncTestWrap([1, 2, 3])))).toEqual([1, 2, 3]);
    });
  });

  it('can be consumed multiple times if its input can', async () => {
    const wrapped = asyncWrap([1, 2, 3]);
    expect(await asyncUnwrap(wrapped)).toEqual([1, 2, 3]);
    expect(await asyncUnwrap(wrapped)).toEqual([1, 2, 3]);
  });
});
