/* @macrome
 * @generated-from ./$last-or.js
 * @generated-by generate/generators/$methods/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncIterableCurry } from '../../internal/async-iterable';

export async function asyncLastOr(iterable, whenEmpty) {
  let _item = whenEmpty;

  for await (const item of iterable) {
    _item = item;
  }

  return _item;
}

export default asyncIterableCurry(asyncLastOr, {
  reduces: true,
});
