/* @macrome
 * @generated-from ./$last-or.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { SourceIterable } from '../../types/iterable';

declare function lastOr<E, T>(whenEmpty: E, iterable: SourceIterable<T>): T | E;

export default lastOr;
