/**
 * @generated-from ./$starts-with.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { SourceIterable } from '../../types/iterable';
declare function startsWith(value: any): (iterable: SourceIterable<any>) => boolean;
declare function startsWith(value: any, iterable: SourceIterable<any>): boolean;
declare function startsWith<V, T>(
  value: V,
  compareEquality: (value: V, item: T) => boolean,
): (iterable: SourceIterable<T>) => boolean;
declare function startsWith<V, T>(
  value: V,
  compareEquality: (value: V, item: T) => boolean,
  iterable: SourceIterable<T>,
): boolean;
export default startsWith;
