/**
 * @generated-from ./$starts-with.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable';
import { startsWithAny } from '../$starts-with-any/starts-with-any';

export function startsWith(iterable, values) {
  return startsWithAny(iterable, [values]);
}

export default iterableCurry(startsWith, {
  reduces: true,
  validateArgs(args) {
    if (true && typeof args[1] === 'string') {
      console.warn('For string inputs use startsWithSeq instead of startsWith');
    }
  },
});
