/**
 * @generated-from ./$starts-with.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { InputIterable } from '../../internal/iterable';
declare function startsWith(value: any): (iterable: InputIterable<any>) => boolean;
declare function startsWith(value: any, iterable: InputIterable<any>): boolean;
export default startsWith;
