/**
 * @generated-from ./$group.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { SourceIterable, ResultIterable } from '../../types/iterable';

declare function group<T>(source: SourceIterable<T>): ResultIterable<[T, ResultIterable<T>]>;

export default group;
