/**
 * @generated-from ./$interpose.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';
import { __interposeSeq } from '../$interpose-seq/interpose-seq.js';

export function __interpose(source, value) {
  return __interposeSeq(source, [value]);
}

export const interpose = /*#__PURE__*/ iterableCurry(__interpose, {
  validateArgs(args) {
    if (true && typeof args[0] === 'string') {
      console.warn(`For string inputs use interposeSeq instead of interpose`);
    }
  },
});
