/**
 * @generated-from ./$window.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';
import { ResultIterable as SyncResultIterable } from '../../types/iterable';

declare function asyncWindow<T>(
  size: number,
  source: AsyncSourceIterable<T>,
): AsyncResultIterable<SyncResultIterable<T>>;

declare function asyncWindow(
  size: number,
): <T>(source: AsyncSourceIterable<T>) => AsyncResultIterable<SyncResultIterable<T>>;

export default asyncWindow;
