/**
 * @generated-from ./$includes-any-subseq.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable } from '../../internal/async-iterable';
import { SourceIterable as SyncSourceIterable } from '../../internal/iterable';
declare function asyncIncludesAnySubseq(
  subseqs: SyncSourceIterable<AsyncSourceIterable<any>>,
): (iterable: AsyncSourceIterable<any>) => Promise<boolean>;
declare function asyncIncludesAnySubseq(
  subseqs: SyncSourceIterable<AsyncSourceIterable<any>>,
  iterable: AsyncSourceIterable<any>,
): Promise<boolean>;
export default asyncIncludesAnySubseq;
