/* @macrome
 * @generated-from ./$includes-any-subseq.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable } from '../../types/async-iterable';
import { SourceIterable as SyncSourceIterable } from '../../types/iterable';

declare function asyncIncludesAnySubseq(
  subseqs: SyncSourceIterable<AsyncSourceIterable<any>>,
): (iterable: AsyncSourceIterable<any>) => Promise<boolean>;

declare function asyncIncludesAnySubseq(
  subseqs: SyncSourceIterable<AsyncSourceIterable<any>>,
  iterable: AsyncSourceIterable<any>,
): Promise<boolean>;

export default asyncIncludesAnySubseq;
