/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$first-or.d.ts#1643837503063
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncFirstOr<E, T>(whenEmpty: E, iterable: AsyncWrappable<T>): Promise<T | E>;

export { asyncFirstOr };
