/**
 * @generated-from ./$includes-seq.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { SourceIterable } from '../../types/iterable';

declare function includesSeq(seq: SourceIterable<any>): (iterable: SourceIterable<any>) => boolean;

declare function includesSeq(seq: SourceIterable<any>, iterable: SourceIterable<any>): boolean;

export { includesSeq };
