/**
 * @generated-from ./$enumerate.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { enumerate } from '@iter-tools/es';
import { wrap, unwrap } from '../../../test/helpers.js';

describe('enumerate', () => {
  describe('when source is empty', () => {
    it('yields no values', () => {
      expect(unwrap(enumerate(null))).toEqual([]);
      expect(unwrap(enumerate(undefined))).toEqual([]);
      expect(unwrap(enumerate(wrap([])))).toEqual([]);
    });
  });

  describe('when source has values', () => {
    it('yields [i, value] tuples', () => {
      expect(unwrap(enumerate(wrap([1, 2, 3])))).toEqual([
        [0, 1],
        [1, 2],
        [2, 3],
      ]);
      expect(unwrap(enumerate(3, wrap([1, 2, 3])))).toEqual([
        [3, 1],
        [4, 2],
        [5, 3],
      ]);
      expect(unwrap(enumerate(-3, wrap([1, 2, 3])))).toEqual([
        [-3, 1],
        [-2, 2],
        [-1, 3],
      ]);
    });
  });
});
