/**
 * @generated-from ./$is-empty.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { InputIterable, Iterable, Promise } from '../../internal/iterable';
declare function isEmpty(iterable: InputIterable<any>): Promise<boolean>;
export default isEmpty;
