/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$includes-any-seq.test.ts#1643837503070
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncIncludesAnySeq } from 'iter-tools-es';
import { asyncWrap } from '../../../test/async-helpers.js';

describe('asyncIncludesAnySeq', () => {
  describe('when no sequences are given', () => {
    it('returns false', async () => {
      expect(await asyncIncludesAnySeq([], asyncWrap([]))).toBe(false);
    });
  });

  describe('when iterable includes a given sequence', () => {
    it('returns true', async () => {
      expect(await asyncIncludesAnySeq([asyncWrap([1, 2])], asyncWrap([1, 2, 3]))).toBe(true);
      expect(
        await asyncIncludesAnySeq([asyncWrap([2, 3]), asyncWrap([1, 2])], asyncWrap([1, 2, 3])),
      ).toBe(true);
      expect(await asyncIncludesAnySeq([asyncWrap([3])], asyncWrap([1, 2, 3]))).toBe(true);
    });
  });

  describe('when iterable is equal to a given sequence', () => {
    it('returns true', async () => {
      expect(await asyncIncludesAnySeq([asyncWrap([1, 2, 3])], asyncWrap([1, 2, 3]))).toBe(true);
    });
  });

  describe('when iterable is shorter than a matching sequence', () => {
    it('returns false', async () => {
      expect(await asyncIncludesAnySeq([asyncWrap([1, 2, 3])], asyncWrap([1, 2]))).toBe(false);
    });
  });

  describe('when iterable is empty', () => {
    describe('and any sequence is empty', () => {
      it('returns true', async () => {
        expect(await asyncIncludesAnySeq([asyncWrap([]), asyncWrap([null])], asyncWrap([]))).toBe(
          true,
        );
        expect(await asyncIncludesAnySeq([null], asyncWrap([]))).toBe(true);
      });
    });

    describe('and no sequence is empty', () => {
      it('returns false', async () => {
        expect(await asyncIncludesAnySeq([asyncWrap([undefined])], asyncWrap([]))).toBe(false);
      });
    });
  });

  describe('when same function is specified', () => {
    const same = (a: number, b: number) => Math.abs(a) === Math.abs(b);
    it('uses same value to do comparison', async () => {
      expect(await asyncIncludesAnySeq(same, [asyncWrap([-2])], asyncWrap([1, 2, 3]))).toBe(true);
      expect(await asyncIncludesAnySeq(() => false, [asyncWrap([2])], asyncWrap([1, 2, 3]))).toBe(
        false,
      );
    });
  });
});
