/**
 * @generated-from ./includes-any-seq.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { includesAnySeq } from 'iter-tools-es';
import { wrap } from '../../../test/helpers.js';

describe('includesAnySeq', () => {
  describe('when no sequences are given', () => {
    it('returns false', () => {
      expect(includesAnySeq([], wrap([]))).toBe(false);
    });
  });

  describe('when iterable includes a given sequence', () => {
    it('returns true', () => {
      expect(includesAnySeq([wrap([1, 2])], wrap([1, 2, 3]))).toBe(true);
      expect(includesAnySeq([wrap([2, 3]), wrap([1, 2])], wrap([1, 2, 3]))).toBe(true);
      expect(includesAnySeq([wrap([3])], wrap([1, 2, 3]))).toBe(true);
    });
  });

  describe('when iterable is equal to a given sequence', () => {
    it('returns true', () => {
      expect(includesAnySeq([wrap([1, 2, 3])], wrap([1, 2, 3]))).toBe(true);
    });
  });

  describe('when iterable is shorter than a matching sequence', () => {
    it('returns false', () => {
      expect(includesAnySeq([wrap([1, 2, 3])], wrap([1, 2]))).toBe(false);
    });
  });

  describe('when iterable is empty', () => {
    describe('and any sequence is empty', () => {
      it('returns true', () => {
        expect(includesAnySeq([wrap([]), wrap([null])], wrap([]))).toBe(true);
        expect(includesAnySeq([null], wrap([]))).toBe(true);
      });
    });

    describe('and no sequence is empty', () => {
      it('returns false', () => {
        expect(includesAnySeq([wrap([undefined])], wrap([]))).toBe(false);
      });
    });
  });
});
