/* @macrome
 * @generated-from ./$group.spec.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import assert from 'static-type-assert';
import { AsyncIterable, AsyncResultIterable } from '../../../types/async-iterable';
import { asyncGroup } from '../../..';

declare const Ø: never;

assert<AsyncResultIterable<[string, AsyncResultIterable<string>]>>(asyncGroup(Ø as string));

assert<AsyncResultIterable<[number, AsyncResultIterable<number>]>>(
  asyncGroup(Ø as AsyncIterable<number>),
);
