/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$unwrap.d.ts#1643837503186
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncIterable } from '../../types/async-iterable';

declare function asyncUnwrap<T>(iterable: AsyncIterable<T>): Array<T>;

declare function asyncUnwrapDeep<T>(iterable: AsyncIterable<AsyncIterable<T>>): Array<Array<T>>;

declare function asyncUnwrapDeep<T>(iterable: T): T;

export { asyncUnwrap, asyncUnwrapDeep };
