/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$bisect.d.ts#1643907550717
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import {
  IterableIterator as SyncIterableIterator,
  Wrappable,
  IterableIterator,
} from '../../types/iterable';

declare function bisect<T>(
  idx: number,
): (source: Wrappable<T>) => SyncIterableIterator<IterableIterator<T>>;

declare function bisect<T>(
  predicate: (value: T, i: number) => any,
): (source: Wrappable<T>) => SyncIterableIterator<IterableIterator<T>>;

declare function bisect<T>(
  idx: number,
  source: Wrappable<T>,
): SyncIterableIterator<IterableIterator<T>>;

declare function bisect<T>(
  predicate: (value: T, i: number) => any,
  source: Wrappable<T>,
): SyncIterableIterator<IterableIterator<T>>;

export { bisect };
