/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$reduce.d.ts#1643907550753
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function reduce<T>(
  reducer: (result: T, value: T, i: number) => T,
): (iterable: Wrappable<T>) => T;

declare function reduce<O, T>(
  reducer: (result: O, value: T, i: number) => O,
): (iterable: Wrappable<T>) => O;

declare function reduce<O, T>(
  initial: O,
  reducer: (result: O, value: T, i: number) => O,
): (iterable: Wrappable<T>) => O;

declare function reduce<T>(
  reducer: (result: T, value: T, i: number) => T,
  iterable: Wrappable<T>,
): T;

declare function reduce<O, T>(
  reducer: (result: O, value: T, i: number) => O,
  iterable: Wrappable<T>,
): O;

declare function reduce<O, T>(
  initial: O,
  reducer: (result: O, value: T, i: number) => O,
  iterable: Wrappable<T>,
): O;

export { reduce };
