/**
 * @generated-from ./$str.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncIterableCurry } from '../../internal/async-iterable.js';

export async function asyncStr(chars) {
  let result = '';

  for await (const char of chars) {
    result += char.toString();
  }

  return result;
}

export default /*#__PURE__*/ asyncIterableCurry(asyncStr, {
  reduces: true,
});
