/**
 * @generated-from ./$filter.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';
declare function asyncFilter<S extends T, T = any>(
  func: (item: T, i: number) => item is S,
): (iterable: AsyncSourceIterable<T>) => AsyncResultIterable<S>;
declare function asyncFilter<T = any>(
  func: (item: T, i: number) => boolean | Promise<boolean>,
): (iterable: AsyncSourceIterable<T>) => AsyncResultIterable<T>;
declare function asyncFilter<S extends T, T = any>(
  func: (item: T, i: number) => item is S,
  iterable: AsyncSourceIterable<T>,
): AsyncResultIterable<S>;
declare function asyncFilter<T = any>(
  func: (item: T, i: number) => boolean | Promise<boolean>,
  iterable: AsyncSourceIterable<T>,
): AsyncResultIterable<T>;
export default asyncFilter;
