/* @macrome
 * @generated-from ./$consume.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable } from '../../types/async-iterable';

declare function asyncConsume<T>(iterable: AsyncSourceIterable<T>): Promise<void>;

export default asyncConsume;
