/**
 * @generated-from ./$split-at.spec.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import assert from 'static-type-assert';
import { ResultIterable as SyncResultIterable } from '../../../types/iterable';
import { Iterable, ResultIterable } from '../../../types/iterable';
import { splitAt } from '../../..';
declare const Ø: never;
assert<SyncResultIterable<ResultIterable<number>>>(splitAt(3, Ø as Iterable<number>));
assert<SyncResultIterable<ResultIterable<number>>>(splitAt(3)(Ø as Iterable<number>));
