/* @macrome
 * @generated-from ./$tap.test.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { tap, toArray, range } from '../../..';

describe('tap', () => {
  it('return tapped iterable', () => {
    const iter = tap(item => item * 2, [1, 2, 3]);
    expect(toArray(iter)).toEqual([1, 2, 3]);
  });

  it('return tapped iterable from iterable', () => {
    const iter = tap(item => item * 2, range(1, 4));
    expect(toArray(iter)).toEqual([1, 2, 3]);
  });

  it('return tapped iterable (curried version)', () => {
    const iter = tap((item: number) => item * 2);
    expect(toArray(iter(range(1, 4)))).toEqual([1, 2, 3]);
  });
});
