/* @macrome
 * @generated-from ./$find-or.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncIterableCurry } from '../../internal/async-iterable';

export async function asyncFindOr(iterable, notFoundValue, func) {
  let c = 0;
  for await (const item of iterable) {
    if (await func(item, c++)) {
      return item;
    }
  }
  return notFoundValue;
}

export default asyncIterableCurry(asyncFindOr, {
  reduces: true,
});
