/* @macrome
 * @generated-from ./$find-or.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { iterableCurry } from '../../internal/iterable';

export function findOr(iterable, notFoundValue, func) {
  let c = 0;
  for (const item of iterable) {
    if (func(item, c++)) {
      return item;
    }
  }
  return notFoundValue;
}

export default iterableCurry(findOr, {
  reduces: true,
});
