/* @macrome
 * @generated-from ./$join-as-string.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { SourceIterable } from '../../types/iterable';

declare function joinAsString(strings: SourceIterable<string>): string;

declare function joinAsString(strings: SourceIterable<SourceIterable<string>>): string;

export default joinAsString;
