/**
 * @generated-from ./$select.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncIterableCurry } from '../../internal/async-iterable.js';

export async function __asyncSelect(iterable, selector) {
  let bestValue;

  for await (const candidate of iterable) {
    if (bestValue === undefined || selector(bestValue, candidate)) {
      bestValue = candidate;
    }
  }

  return bestValue;
}

export const asyncSelect = asyncIterableCurry(__asyncSelect, {
  reduces: true,
});
