/**
 * @generated-from ./$find-or.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncIterableCurry } from '../../internal/async-iterable.js';

export async function asyncFindOr(iterable, notFoundValue, func) {
  let c = 0;
  for await (const value of iterable) {
    if (await func(value, c++)) {
      return value;
    }
  }
  return notFoundValue;
}

export default /*#__PURE__*/ asyncIterableCurry(asyncFindOr, {
  reduces: true,
});
