/**
 * @generated-from ./$drop.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';

export function* __drop(iterable, n) {
  let i = 0;
  for (const value of iterable) {
    if (i++ >= n) yield value;
  }
}

export const drop = /*#__PURE__*/ iterableCurry(__drop);
