/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$starts-with-seq.d.ts#1643837503103
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncStartsWithSeq(
  same: (a: any, b: any) => boolean,
  seq: AsyncWrappable<any>,
): (iterable: AsyncWrappable<any>) => Promise<boolean>;

declare function asyncStartsWithSeq(
  same: (a: any, b: any) => boolean,
  seq: AsyncWrappable<any>,
  iterable: AsyncWrappable<any>,
): Promise<boolean>;

declare function asyncStartsWithSeq(
  seq: AsyncWrappable<any>,
  iterable: AsyncWrappable<any>,
): Promise<boolean>;

export { asyncStartsWithSeq };
