/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$split.test.ts#1643907550765
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncSplit } from 'iter-tools-es';
import { asyncWrap, asyncUnwrapDeep } from '../../../test/async-helpers.js';

describe('asyncSplit', () => {
  it('should yield an iterable for every value in the iterable', async () => {
    expect(await asyncUnwrapDeep(asyncSplit(asyncWrap([1, 2, 3])))).toEqual([[1], [2], [3]]);
  });
});
