/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$is-empty.test.ts#1643837503077
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { isEmpty } from 'iter-tools-es';
import { wrap } from '../../../test/helpers.js';

describe('isEmpty', () => {
  describe('when iterable is empty', () => {
    it('returns true', () => {
      expect(isEmpty(null)).toBe(true);
      expect(isEmpty(undefined)).toBe(true);
      expect(isEmpty(wrap([]))).toBe(true);
    });
  });

  describe('when iterable has values', () => {
    it('returns false', () => {
      expect(isEmpty(wrap([1]))).toBe(false);
      expect(isEmpty(wrap([1, 2]))).toBe(false);
    });
  });
});
