/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$first.test.ts#1643837503064
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { first } from 'iter-tools-es';
import { wrap } from '../../../test/helpers.js';

describe('first', () => {
  describe('when iterable is empty', () => {
    it('returns undefined', () => {
      expect(first(null)).toBe(undefined);
      expect(first(undefined)).toBe(undefined);
      expect(first(wrap([]))).toBe(undefined);
    });
  });

  describe('when iterable has values', () => {
    it('returns first value', () => {
      expect(first(wrap([1, 2, 3]))).toBe(1);
    });
  });
});
