/**
 * @generated-from ./$interpose-seq.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';

declare function asyncInterposeSeq<V>(
  seq: AsyncSourceIterable<V>,
): <T>(source: AsyncSourceIterable<T>) => AsyncResultIterable<T | V>;

declare function asyncInterposeSeq<V, T>(
  seq: AsyncSourceIterable<V>,
  source: AsyncSourceIterable<T>,
): AsyncResultIterable<T | V>;

export { asyncInterposeSeq };
