/**
 * @generated-from ./$group-by.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable';
import { spliterateGrouped } from '../$spliterate-grouped/spliterate-grouped';
import { peekerate } from '../$peekerate/peekerate';

const initialKey = Symbol('initial group key');

let warnedNullGetKeyDeprecation = false;

const warnNullGetKeyDeprecation = () => {
  if (!warnedNullGetKeyDeprecation) {
    console.warn(
      `\`${'groupBy'}(null, iterable)\` is deprecated and will be removed in iter-tools@8. ` +
        `Instead use ${'group'}(iterable)`,
    );
    warnedNullGetKeyDeprecation = true;
  }
};

function* groupingSpliterator(split, { getKey }, source) {
  const peekr = peekerate(source);
  let key = initialKey;
  let idx = 0;

  while (!peekr.done) {
    const lastKey = key;

    key = getKey(peekr.value, idx++);

    if (lastKey !== key) {
      yield split;
      yield key;
    }

    yield peekr.value;

    peekr.advance();
  }
}

export function groupBy(source, getKey) {
  if (getKey === null) {
    warnNullGetKeyDeprecation();
    getKey = _ => _;
  }

  return spliterateGrouped(source, groupingSpliterator, { getKey });
}

export default iterableCurry(groupBy);
