/**
 * @generated-from ./$flat.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncIterableCurry, asyncIsLoopable } from '../../internal/async-iterable.js';
import { validateArgs } from './internal/validate-args.js';

const defaultShouldFlat = (value) => typeof value !== 'string' && asyncIsLoopable(value);

async function* asyncFlatInternal(shouldFlat, depth, currentDepth, source) {
  for await (const value of source) {
    if (currentDepth < depth && (await shouldFlat(value))) {
      yield* asyncFlatInternal(shouldFlat, depth, currentDepth + 1, value);
    } else {
      yield value;
    }
  }
}

export function asyncFlat(source, shouldFlat = defaultShouldFlat, depth = 1) {
  return asyncFlatInternal(shouldFlat, depth, 0, source);
}

export default /*#__PURE__*/ asyncIterableCurry(asyncFlat, {
  minArgs: 0,
  maxArgs: 2,
  validateArgs,
});
