/**
 * @generated-from ./$tap.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable, AsyncResultIterable } from '../../internal/async-iterable';
declare function asyncTap<T = any>(
  func: (item: T, i: number) => any | Promise<any>,
): (iterable: AsyncSourceIterable<T>) => AsyncResultIterable<T>;
declare function asyncTap<T = any>(
  func: (item: T, i: number) => any | Promise<any>,
  iterable: AsyncSourceIterable<T>,
): AsyncResultIterable<T>;
export default asyncTap;
