/**
 * @generated-from ./$fork.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { ResultIterable as SyncResultIterable } from '../../internal/iterable';
import { SourceIterable, ResultIterable } from '../../internal/iterable';
declare function fork<T = any>(iterable: SourceIterable<T>): SyncResultIterable<ResultIterable<T>>;
declare function fork<T = any>(
  n: number,
): (iterable: SourceIterable<T>) => SyncResultIterable<ResultIterable<T>>;
declare function fork<T = any>(
  n: number,
  iterable: SourceIterable<T>,
): SyncResultIterable<ResultIterable<T>>;
export default fork;
