/* @macrome
 * @generated-from ./$first.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { firstOr } from '../$first-or/first-or';

export function first(iterable) {
  return firstOr(iterable, undefined);
}

export default first;
