/**
 * @generated-from ./$includes-subseq.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable } from '../../types/async-iterable';
declare function asyncIncludesSubseq(
  subseq: AsyncSourceIterable<any>,
): (iterable: AsyncSourceIterable<any>) => Promise<boolean>;
declare function asyncIncludesSubseq(
  subseq: AsyncSourceIterable<any>,
  iterable: AsyncSourceIterable<any>,
): Promise<boolean>;
declare function asyncIncludesSubseq<V, T>(
  subseq: AsyncSourceIterable<V>,
  compareEquality: (value: V, item: T) => boolean,
): (iterable: AsyncSourceIterable<T>) => Promise<boolean>;
declare function asyncIncludesSubseq<V, T>(
  subseq: AsyncSourceIterable<V>,
  compareEquality: (value: V, item: T) => boolean,
  iterable: AsyncSourceIterable<T>,
): Promise<boolean>;
export default asyncIncludesSubseq;
