/**
 * @generated-from ./$window-behind.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';
import { IterableIterator as SyncIterableIterator } from '../../types/iterable';

declare function asyncWindowBehind<T, Filler = undefined>(
  opts: {
    readonly filler?: Filler;
  },
  size: number,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<SyncIterableIterator<T | Filler>>;

declare function asyncWindowBehind<T>(
  size: number,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<SyncIterableIterator<T | undefined>>;

declare function asyncWindowBehind(
  opts: {
    readonly filler: any;
  },
  size: number,
): <T>(source: AsyncWrappable<T>) => AsyncIterableIterator<SyncIterableIterator<T>>;

declare function asyncWindowBehind(
  size: number,
): <T>(source: AsyncWrappable<T>) => AsyncIterableIterator<SyncIterableIterator<T | undefined>>;

export { asyncWindowBehind };
