/**
 * @generated-from ./async-enumerate.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncEnumerate, asyncToArray, range } from '..';
describe('asyncEnumerate', () => {
  it('enumerates iterables', async () => {
    const iter = asyncEnumerate(
      range({
        start: 1,
        end: 4,
      }),
    );
    expect(await asyncToArray(iter)).toEqual([[0, 1], [1, 2], [2, 3]]);
  });
  it('enumerates iterables with start', async () => {
    const iter = asyncEnumerate(
      range({
        start: 1,
        end: 4,
      }),
      3,
    );
    expect(await asyncToArray(iter)).toEqual([[3, 1], [4, 2], [5, 3]]);
  });
});
