/* @macrome
 * @generated-from ./$range.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncResultIterable } from '../types/async-iterable';

declare function asyncRange(start: number, end: number, step?: number): AsyncResultIterable<number>;

export { asyncRange };
