/**
 * @generated-from ./$compress.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

/* eslint-disable no-unused-vars */

import { asyncCompress, asyncToArray, range } from '../..'
describe('asyncCompress', () => {
  it('compress iterables', async () => {
    const iter = asyncCompress(range(10), [0, 1, 0, 1, 1])
    expect((await asyncToArray(iter))).toEqual([1, 3, 4])
  })
})
