/* @macrome
 * @generated-from ./$range.js
 * @generated-by generate/generators/$tests/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncWrap } from './__framework__/async-wrap';

async function* genRange(start, end, step = 1) {
  for (let i = start; i < end; i += step) {
    yield i;
  }
}

export function asyncRange(start, end, step) {
  return asyncWrap(genRange(start, end, step));
}
