/**
 * @generated-from ./$consume.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

/* eslint-disable no-unused-vars */

import { consume } from '../..'
describe('consume', () => {
  it('consumes an iterable', () => {
    const arr = []
    consume(item => arr.push(item), [1, 2, 3])
    expect(arr).toEqual([1, 2, 3])
  })
  it('consumes an iterable using a promise', () => {
    const arr = []
    consume(item => {
      arr.push(item)
      return Promise.resolve(0)
    }, [1, 2, 3])
    expect(arr).toEqual([1, 2, 3])
  })
  it('consumes an iterable (curried)', () => {
    const arr = []
    const consumePush = consume(item => arr.push(item))
    consumePush([1, 2, 3])
    expect(arr).toEqual([1, 2, 3])
  })
})
