/* @macrome
 * @generated-from ./$helpers.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export function unwrapDeep<T>(iterable: T): T;
