/**
 * @generated-from ./$interleave.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry, callReturn } from '../../internal/iterable.js';
import { parallelEach } from '../../internal/parallel-each.js';
import { Peekerator } from '../../internal/peekerator.js';
import { map } from '../$map/map.js';
import { toArray } from '../$to-array/to-array.js';

const _ = Symbol.for('_');
const __advance = Symbol.for('__advance');

class SummarizedPeekerator extends Peekerator {
  constructor(iterator, first, inputSummary) {
    super(iterator, first);
    this[_].inputSummary = inputSummary;
  }

  advance() {
    this[_].inputSummary.advanceBuffer(this);
  }

  [__advance]() {
    super.advance();
  }
}

class InputSummaryInternal {
  constructor() {
    this.buffers = [];
    this.notDoneBuffer = null;
    this.index = 0;
  }

  init(buffers) {
    this.buffers = buffers;
    this.updateNotDone();
  }

  updateNotDone() {
    this.notDoneBuffer = this.buffers.find((buffer) => !buffer.done);
  }

  advanceBuffer(buffer) {
    const wasDone = buffer.done;

    buffer[__advance]();
    this.index++;

    if (!wasDone && buffer.done) {
      this.updateNotDone();
    }
  }
}

export class InputSummary {
  constructor(internal) {
    this[_] = internal;
  }

  advance() {
    throw new Error('advance() is not supported on an interleave summary');
  }

  get current() {
    return { done: this.done, value: this.value };
  }

  get value() {
    return this[_].notDoneBuffer;
  }

  get done() {
    return this[_].notDoneBuffer === undefined;
  }

  get index() {
    return this[_].index;
  }
}

class Interleaver {
  constructor(sources, strategy, options) {
    this.sources = sources;
    this.strategy = strategy;
    this.options = options;

    this.initialized = false;
    this.inputSummary = new InputSummaryInternal(sources);
  }

  init() {
    this.initialized = true;
    const { strategy, options, inputSummary } = this;
    this.buffers = toArray(
      map(this.sources, (source) => SummarizedPeekerator.from(source, inputSummary)),
    );
    this.iterator = strategy(options, new InputSummary(inputSummary), ...this.buffers);

    inputSummary.init(this.buffers);
  }

  returnBuffers() {
    parallelEach(this.buffers, (buffer) => buffer.return());
  }

  next() {
    if (!this.initialized) this.init();

    const item = this.iterator.next();
    if (item.done) this.returnBuffers();
    return item;
  }

  return() {
    callReturn(this.iterator);
    this.returnBuffers();
  }
}

export function interleave(sources, strategy, options = {}) {
  return new Interleaver(sources, strategy, options);
}

export default /*#__PURE__*/ iterableCurry(interleave, {
  variadic: true,
  optionalArgsAtEnd: true,
  minArgs: 1,
  maxArgs: 2,
});
