/**
 * @generated-from ./compose.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { compose } from '@iter-tools/es';

describe('compose', () => {
  it('works', () => {
    const a = (str: string) => `a(${str})`;
    const b = (str: string) => `b(${str})`;

    expect(compose(a, b)('input')).toBe('a(b(input))');
  });

  it('works with types', () => {
    expect(
      compose(
        (v: number): boolean => Boolean(v),
        (v: string): number => Number(v),
      )(''),
    ).toBe(false);
  });

  it('is the identity function when no functions are passed', () => {
    expect(compose()(true)).toBe(true);
  });
});
