/**
 * @generated-from ./$join-as-string-with.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { SourceIterable } from '../../types/iterable';
declare function joinAsStringWith(separator: string, strings: SourceIterable<string>): string;
declare function joinAsStringWith(
  separator: string,
  strings: SourceIterable<SourceIterable<string>>,
): string;
declare function joinAsStringWith(separator: string): (strings: SourceIterable<string>) => string;
declare function joinAsStringWith(
  separator: string,
): (strings: SourceIterable<SourceIterable<string>>) => string;
export default joinAsStringWith;
