/**
 * @generated-from ./$interpose.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable';
import { interposeSubseq } from '../$interpose-subseq/interpose-subseq';

export function interpose(source, value) {
  return interposeSubseq(source, [value]);
}

export default iterableCurry(interpose, {
  validateArgs(args) {
    if (true && typeof args[1] === 'string') {
      console.warn(`For string inputs use interposeSubseq instead of interpose`);
    }
  },
});
