/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$spliterate.d.ts#1643907550766
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
declare function asyncSpliterate(...args: Array<any>): any;

declare const split: symbol;

export { split };

export { asyncSpliterate };
