/**
 * @generated-from ./$last.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

/* eslint-disable no-unused-vars,import/no-duplicates,no-constant-condition */

import { asyncLast } from '../../..';
import { asyncWrap } from '../../../test/async-helpers';

describe('asyncLast', () => {
  describe('when iterable is empty', () => {
    it('returns undefined', async () => {
      expect(await asyncLast(null)).toBe(undefined);
      expect(await asyncLast(undefined)).toBe(undefined);
      expect(await asyncLast(asyncWrap([]))).toBe(undefined);
    });
  });

  describe('when iterable has values', () => {
    it('returns last value', async () => {
      expect(await asyncLast(asyncWrap([1, 2, 3]))).toBe(3);
    });
  });
});
