/* @macrome
 * @generated-from ./$is-sorted.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable } from '../../types/async-iterable';

declare function asyncIsSorted(iterable: AsyncSourceIterable<any>): boolean | Promise<boolean>;

declare function asyncIsSorted<T>(
  comparator: (a: T, b: T) => number,
  iterable: AsyncSourceIterable<T>,
): boolean | Promise<boolean>;

export default asyncIsSorted;
