/**
 * @generated-from ./$first-or.spec.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import assert from 'static-type-assert';
import { AsyncIterable, AsyncPromise } from '../../../internal/async-iterable';
import { asyncFirstOr } from '../../..';
declare var Ø: never;
assert<AsyncPromise<null>>(asyncFirstOr(Ø as null, Ø as []));
assert<AsyncPromise<0>>(asyncFirstOr(Ø as null, Ø as [0, 1, 2, 3]));
assert<AsyncPromise<number>>(asyncFirstOr(Ø as null, Ø as [number, ...any[]]));
assert<AsyncPromise<number | null>>(asyncFirstOr(Ø as null, Ø as AsyncIterable<number>));
assert<AsyncPromise<string | null>>(asyncFirstOr(Ø as null, Ø as string));
