/* @macrome
 * @generated-from ./$first-or.spec.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import assert from 'static-type-assert';
import { Iterable } from '../../../types/iterable';
import { firstOr } from '../../..';

declare const Ø: never;

assert<null>(firstOr(Ø as null, Ø as []));

assert<0>(firstOr(Ø as null, Ø as [0, 1, 2, 3]));

assert<number>(firstOr(Ø as null, Ø as [number, ...any[]]));

assert<number | null>(firstOr(Ø as null, Ø as Iterable<number>));

assert<string | null>(firstOr(Ø as null, Ø as string));
