/**
 * @generated-from ./$zip-all.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { Wrappable, IterableIterator } from '../../types/iterable';

declare function zipAll<F, T>(
  options: { filler?: F },
  ...sources: Array<Wrappable<T>>
): IterableIterator<Array<T | F>>;

declare function zipAll<T>(...sources: Array<Wrappable<T>>): IterableIterator<Array<T | undefined>>;

export { zipAll };
