/**
 * @generated-from ./$max-by.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { Wrappable } from '../../types/iterable';

declare function maxBy<T, K>(mapper: (item: T) => K): (iterable: Wrappable<T>) => T | undefined;

declare function maxBy<T, K>(mapper: (item: T) => K, iterable: Wrappable<T>): T | undefined;

declare function maxBy<T, K>(
  mapper: (item: T) => K,
  compare: (a: K, b: K) => number,
): (iterable: Wrappable<T>) => T | undefined;

declare function maxBy<T, K>(
  mapper: (item: T) => K,
  compare: (a: K, b: K) => number,
  iterable: Wrappable<T>,
): T | undefined;

export { maxBy };
