/* @macrome
 * @generated-from ./$to-array.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable } from '../../types/async-iterable';

declare function asyncToArray<T>(source: AsyncSourceIterable<T>): T[] | Promise<T[]>;

export default asyncToArray;
