/* @macrome
 * @generated-from ./$to-array.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { SourceIterable } from '../../types/iterable';

declare function toArray<T>(source: SourceIterable<T>): T[];

export default toArray;
