/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$wrap.d.ts#1643837503186
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncWrap<T>(array: AsyncWrappable<T>): AsyncIterableIterator<T>;
declare function asyncWrap(string: string): AsyncIterableIterator<string>;

declare function asyncWrapDeep<T>(
  array: AsyncWrappable<T | AsyncWrappable<T | AsyncWrappable<T>>>,
): AsyncIterableIterator<AsyncIterableIterator<T>>;

export { asyncWrap, asyncWrapDeep };
