/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/array-reverse/array-reverse.js#1643837503123
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __arrayReverse as default } from '../impls/array-reverse/array-reverse.js';
