/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$zip-all/async-zip-all.js#1643837503119
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __asyncZipAll as default } from '../impls/$zip-all/async-zip-all.js';
