/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$is-empty/is-empty.js#1643837503078
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __isEmpty as default } from '../impls/$is-empty/is-empty.js';
