/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$split-when/split-when.js#1643837503098
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __splitWhen as default } from '../impls/$split-when/split-when.js';
