/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$str/str.js#1643837503106
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __str as default } from '../impls/$str/str.js';
