/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$window-behind/window-behind.js#1643837503116
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __windowBehind as default } from '../impls/$window-behind/window-behind.js';
