/**
 * @generated-from ./$take-last.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';
import { takeLastOr } from '../$take-last-or/take-last-or.js';

export function takeLast(iterable) {
  return takeLastOr(iterable, undefined);
}

export default /*#__PURE__*/ iterableCurry(takeLast, {
  reduces: true,
});
