/**
 * @generated-from ./take-last.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { takeLast } from 'iter-tools-es';
import { wrap } from '../../../test/helpers.js';

describe('takeLast', () => {
  describe('when iterable is empty', () => {
    it('returns undefined', () => {
      expect(takeLast(null)).toBe(undefined);
      expect(takeLast(undefined)).toBe(undefined);
      expect(takeLast(wrap([]))).toBe(undefined);
    });
  });

  describe('when iterable has values', () => {
    it('returns last value', () => {
      expect(takeLast(wrap([1, 2, 3]))).toBe(3);
    });
  });
});
