/**
 * @generated-from ./$is-empty.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncSourceIterable } from '../../types/async-iterable';

declare function asyncIsEmpty(iterable: AsyncSourceIterable<any>): Promise<boolean>;

export { asyncIsEmpty };
