/**
 * @generated-from ./$is-empty.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';
import { __firstOr } from '../$first-or/first-or.js';

const none = Symbol('none');

export function __isEmpty(iterable) {
  return __firstOr(iterable, none) === none;
}

export const isEmpty = /*#__PURE__*/ iterableCurry(__isEmpty, {
  reduces: true,
});
