/**
 * @generated-from ./$reverse.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncIterableCurry } from '../../internal/async-iterable.js';
import { __asyncToArray } from '../$to-array/async-to-array.js';

export async function* __asyncReverse(source) {
  yield* (await __asyncToArray(source)).reverse();
}

export const asyncReverse = /*#__PURE__*/ asyncIterableCurry(__asyncReverse);
