/* @macrome
 * @generated-from ./$drop-while.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';

declare function asyncDropWhile<T>(
  predicate: (item: T, i: number) => boolean | Promise<boolean>,
): (source: AsyncSourceIterable<T>) => AsyncResultIterable<T>;

declare function asyncDropWhile<T>(
  predicate: (item: T, i: number) => boolean | Promise<boolean>,
  source: AsyncSourceIterable<T>,
): AsyncResultIterable<T>;

export default asyncDropWhile;
