/**
 * @generated-from ./$flat-map.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

/* eslint-disable no-unused-vars,import/no-duplicates,no-constant-condition */

import { flatMap } from '../../..';
import { wrap, unwrap } from '../../../test/helpers';

describe('flatMap', () => {
  describe('when source is empty', () => {
    it('yields no values', () => {
      expect(unwrap(flatMap((value: any) => value, null))).toEqual([]);
      expect(unwrap(flatMap((value: any) => value, undefined))).toEqual([]);
      expect(unwrap(flatMap((value: any) => value, wrap([])))).toEqual([]);
    });
  });

  describe('when source has values', () => {
    it('concatenates result of func(value, i) for each value in source', () => {
      const iter = flatMap((value: number, i: number) => [i, value], wrap([1, 2, 3]));
      expect(unwrap(iter)).toEqual([0, 1, 1, 2, 2, 3]);
    });
  });
});
