/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$any-seq.js#1643907550813
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { ensureIterable } from './iterable.js';
import { __toArray } from '../impls/$to-array/to-array.js';
import { __map } from '../impls/$map/map.js';

export function seqsToArray(values) {
  return __toArray(
    __map(values, (value) => __toArray(ensureIterable(value))),
    (arr) => arr.length > 0,
  );
}
