/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$wrap.js#1643907550813
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import {
  _awaitAsyncGenerator as _awaitAsyncGenerator4,
  _wrapAsyncGenerator as _wrapAsyncGenerator2,
  _awaitAsyncGenerator as _awaitAsyncGenerator3,
  _asyncIterator as _asyncIterator2,
  _asyncGeneratorDelegate as _asyncGeneratorDelegate2,
  _awaitAsyncGenerator as _awaitAsyncGenerator2,
  _wrapAsyncGenerator,
  _awaitAsyncGenerator,
  _asyncIterator,
  _asyncGeneratorDelegate,
} from '../internal/asyncish.js';

export function asyncWrap(_x) {
  return _$wrap.apply(this, arguments);
}

function _$wrap() {
  _$wrap = _wrapAsyncGenerator(function* (source) {
    yield* _asyncGeneratorDelegate(_asyncIterator(source), _awaitAsyncGenerator);
  });

  return _$wrap.apply(this, arguments);
}

export function asyncNullableWrap(_x2) {
  return _$nullableWrap.apply(this, arguments);
}

function _$nullableWrap() {
  _$nullableWrap = _wrapAsyncGenerator2(function* (source) {
    if (source != null) {
      yield* _asyncGeneratorDelegate2(_asyncIterator2(source), _awaitAsyncGenerator3);
    }
  });

  return _$nullableWrap.apply(this, arguments);
}
