/**
 * @generated-from ./$ensure-subseqs.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import toArray from '../methods/$to-array/to-array';
import map from '../methods/$map/map';
export function ensureSubseqs(valueSubseqs) {
  return toArray(
    map(value => {
      return true && typeof value === 'string' ? value : toArray(value);
    }, valueSubseqs),
  );
}
