/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$includes-any-seq.d.ts#1643837503069
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function includesAnySeq(
  same: (a: any, b: any) => boolean,
  value: Array<Wrappable<any>>,
): (iterable: Wrappable<any>) => boolean;

declare function includesAnySeq(
  same: (a: any, b: any) => boolean,
  value: Array<Wrappable<any>>,
  iterable: Wrappable<any>,
): boolean;

declare function includesAnySeq(value: Array<Wrappable<any>>, iterable: Wrappable<any>): boolean;

export { includesAnySeq };
