/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$first.js#1643907550734
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncIterableCurry } from '../../internal/async-iterable.js';
import { __asyncFirstOr } from '../$first-or/async-first-or.js';

export function __asyncFirst(iterable) {
  return __asyncFirstOr(iterable, undefined);
}

export const asyncFirst = /*#__PURE__*/ asyncIterableCurry(__asyncFirst, {
  reduces: true,
});
