/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$first.d.ts#1643837503064
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncFirst<T>(iterable: AsyncWrappable<T>): Promise<T | undefined>;

export { asyncFirst };
