/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$first.js#1643907550734
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { iterableCurry } from '../../internal/iterable.js';
import { __firstOr } from '../$first-or/first-or.js';

export function __first(iterable) {
  return __firstOr(iterable, undefined);
}

export const first = /*#__PURE__*/ iterableCurry(__first, {
  reduces: true,
});
