/**
 * @generated-from ./$first.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';
import { __firstOr } from '../$first-or/first-or.js';

export function __first(iterable) {
  return __firstOr(iterable, undefined);
}

export const first = /*#__PURE__*/ iterableCurry(__first, {
  reduces: true,
});
