/**
 * @generated-from ./not-loopable.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { notLoopable } from '@iter-tools/es';

describe('notLoopable', () => {
  describe('when value has Symbol.iterator', () => {
    it('returns false', () => {
      expect(notLoopable([])).toBe(false);
      expect(notLoopable(new Map())).toBe(false);
      expect(notLoopable(new Set())).toBe(false);
      expect(notLoopable({ [Symbol.iterator]: null })).toBe(false);
    });
  });

  describe('when value does not have Symbol.iterator', () => {
    it('returns true', () => {
      expect(notLoopable(undefined)).toBe(true);
      expect(notLoopable(null)).toBe(true);
      expect(notLoopable(42)).toBe(true);
      expect(notLoopable({})).toBe(true);
    });
  });
});
