/**
 * @generated-from ./$find.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';
import { __findOr } from '../$find-or/find-or.js';

export function __find(iterable, predicate) {
  return __findOr(iterable, undefined, predicate);
}

export const find = /*#__PURE__*/ iterableCurry(__find, {
  reduces: true,
});
