/* @macrome
 * @generated-from ./null-or-async.test.js
 * @generated-by generate/generators/type-tests/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { nullOrAsync, arrayFromAsync } from '../../..';

describe('nullOrAsync', () => {
  it('empty array returns null', async () => {
    expect(await nullOrAsync([])).toEqual(null);
  });

  it('null returns null', async () => {
    expect(await nullOrAsync(null)).toEqual(null);
  });

  it('iterable returns iterable', async () => {
    expect(await arrayFromAsync(await nullOrAsync([1, 2, 3]))).toEqual([1, 2, 3]);
  });
});
