/* @macrome
 * @generated-from ./$zip-all.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';

declare function asyncZipAll<F, T>(
  options: {
    filler?: F;
  },
  ...sources: Array<AsyncSourceIterable<T>>
): AsyncResultIterable<Array<T | F>>;

declare function asyncZipAll<T>(
  ...sources: Array<AsyncSourceIterable<T>>
): AsyncResultIterable<Array<T | undefined>>;

export default asyncZipAll;
