/* @macrome
 * @generated-from ./$zip-all.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { SourceIterable, ResultIterable } from '../../types/iterable';

declare function zipAll<F, T>(
  options: {
    filler?: F;
  },
  ...sources: Array<SourceIterable<T>>
): ResultIterable<Array<T | F>>;

declare function zipAll<T>(
  ...sources: Array<SourceIterable<T>>
): ResultIterable<Array<T | undefined>>;

export default zipAll;
