/* @macrome
 * @generated-from ./join-as-string-with.test.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { joinAsStringWith } from '../../..';

describe('joinAsStringWith', () => {
  it('joins with the empty string', () => {
    expect(joinAsStringWith('', [['a'], ['b'], ['c']])).toBe('abc');
  });

  it('joins with specified separator', () => {
    expect(joinAsStringWith(' ', [['a'], ['b'], ['c']])).toBe('a b c');
  });

  it('joins an iterable of strings', () => {
    expect(joinAsStringWith(' ', ['a', 'b', 'c'])).toBe('a b c');
  });

  it('turns the empty iterable into the empty string', () => {
    expect(joinAsStringWith(' ', null)).toBe('');
  });
});
