/**
 * @generated-from ./$equal.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { Wrappable } from '../../types/iterable';

declare function equal(...iterables: Array<Wrappable<any>>): boolean;

export { equal };
