/* @macrome
 * @generated-from ./$last.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncLastOr } from '../$last-or/async-last-or';

export function asyncLast(iterable) {
  return asyncLastOr(iterable, undefined);
}

export default asyncLast;
