/* @macrome
 * @generated-from ./$last.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { SourceIterable } from '../../types/iterable';

declare function last<T>(iterable: SourceIterable<T>): T | undefined;

export default last;
