/* @macrome
 * @generated-from ./$cycle.d.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';

declare function asyncCycle<T>(iterable: AsyncSourceIterable<T>): AsyncResultIterable<T>;

export default asyncCycle;
