/**
 * @generated-from ./$group-by.spec.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import assert from 'static-type-assert';
import { Iterable, ResultSubseqIterable } from '../../../types/iterable';
import { EntryIterable } from '../../../types/entry-iterable';
import { groupBy } from '../../..';
declare const Ø: never;
assert<EntryIterable<string, ResultSubseqIterable<number>>>(
  groupBy(Ø as (x: number) => string)(Ø as Iterable<number>),
);
assert<EntryIterable<string, ResultSubseqIterable<number>>>(
  groupBy(Ø as (x: number) => string, Ø as Iterable<number>),
);
