/**
 * @generated-from ./async-cycle-times.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncCycleTimes } from 'iter-tools-es';
import { asyncWrap, asyncUnwrap } from '../../../test/async-helpers.js';

describe('asyncCycleTimes', () => {
  describe('when source is empty', () => {
    it('yields no values', async () => {
      expect(await asyncUnwrap(asyncCycleTimes(1, null))).toEqual([]);
      expect(await asyncUnwrap(asyncCycleTimes(1, undefined))).toEqual([]);
      expect(await asyncUnwrap(asyncCycleTimes(1, []))).toEqual([]);
    });
  });

  describe('when source has values', () => {
    it('yields those values repeating n times', async () => {
      expect(await asyncUnwrap(asyncCycleTimes(2, asyncWrap([1, 2, 3])))).toEqual([
        1,
        2,
        3,
        1,
        2,
        3,
      ]);
    });
  });
});
