/* @macrome
 * @generated-from ./$size.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncEnsureIterable } from '../../internal/async-iterable';

export async function asyncSize(iterable) {
  const iter = asyncEnsureIterable(iterable);
  let size = 0;

  // eslint-disable-next-line no-unused-vars
  for await (const _ of iter) {
    size++;
  }
  return size;
}

export default asyncSize;
