/**
 * @generated-from ./$size.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncInputIterable, AsyncPromise } from '../../internal/async-iterable';
declare function asyncSize<Iter extends AsyncInputIterable<any>>(
  iterable: Iter,
): AsyncPromise<Iter extends any[] ? Iter['length'] : number>;
export default asyncSize;
