/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$window.d.ts#1643837503116
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';
import { IterableIterator as SyncIterableIterator } from '../../types/iterable';

declare function asyncWindow<T>(
  size: number,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<SyncIterableIterator<T>>;

declare function asyncWindow(
  size: number,
): <T>(source: AsyncWrappable<T>) => AsyncIterableIterator<SyncIterableIterator<T>>;

export { asyncWindow };
