/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$window.d.ts#1643907550785
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import {
  Wrappable,
  IterableIterator,
  IterableIterator as SyncIterableIterator,
} from '../../types/iterable';

declare function window<T>(
  size: number,
  source: Wrappable<T>,
): IterableIterator<SyncIterableIterator<T>>;

declare function window(
  size: number,
): <T>(source: Wrappable<T>) => IterableIterator<SyncIterableIterator<T>>;

export { window };
