/**
 * @generated-from ./async-join.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

/* eslint-disable no-unused-vars,import/no-duplicates,no-constant-condition */

import { asyncJoin, asyncToArray } from '../../..';

describe('asyncJoin', () => {
  it('should join each group with the provided value', async () => {
    expect(await asyncToArray(asyncJoin([[1], [2], [3]]))).toEqual([1, 2, 3]);
  });

  it('should have two adjacent separators when encountering an empty group', async () => {
    expect(await asyncToArray(asyncJoin([[1], [], [3]]))).toEqual([1, 3]);
  });

  it('should yield a single separator when joining two empty groups', async () => {
    expect(await asyncToArray(asyncJoin([[], []]))).toEqual([]);
  });

  it('passes through the empty iterable', async () => {
    expect(await asyncToArray(asyncJoin(null))).toEqual([]);
  });
});
