/**
 * @generated-from ./$peekerate.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { Peekerator } from '../../internal/peekerator';

// This is for the benefit of the type system.
// In TS an identifier cannot represent a type *and* a value, and I need both.
export { Peekerator, Peekerator as PeekeratorClass };

export function peekerate(source) {
  return Peekerator.from(source);
}

export default peekerate;
