/**
 * @generated-from ./$split-on-subseq.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { SourceIterable, ResultIterable } from '../../internal/iterable';
declare function splitOnSubseq(
  subseq: SourceIterable<any>,
): <T = any>(iterable: SourceIterable<T>) => ResultIterable<ResultIterable<T>>;
declare function splitOnSubseq<T = any>(
  subseq: SourceIterable<any>,
  iterable: SourceIterable<T>,
): ResultIterable<ResultIterable<T>>;
export default splitOnSubseq;
