/**
 * @generated-from ./$first.spec.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import assert from 'static-type-assert';
import { Iterable } from '../../../internal/iterable';
import { first } from '../../..';
declare const Ø: never;
assert<undefined>(first(Ø as []));
assert<0>(first(Ø as [0, 1, 2, 3]));
assert<number>(first(Ø as [number, ...any[]]));
assert<number | undefined>(first(Ø as Iterable<number>));
assert<string | undefined>(first(Ø as string));
