/* @macrome
 * @generated-from ./$first.spec.ts
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import assert from 'static-type-assert';
import { Iterable } from '../../../types/iterable';
import { first } from '../../..';

declare const Ø: never;

assert<undefined>(first(Ø as []));

assert<0>(first(Ø as [0, 1, 2, 3]));

assert<number>(first(Ø as [number, ...any[]]));

assert<number | undefined>(first(Ø as Iterable<number>));

assert<string | undefined>(first(Ø as string));
