/**
 * @generated-from ./$join.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncWrapWithResultIterable, asyncEnsureIterable } from '../../internal/async-iterable.js';
import { asyncJoinWithSeq } from '../$join-with-seq/async-join-with-seq.js';

const emptySeq = [];

export function asyncJoin(source) {
  return asyncJoinWithSeq(asyncEnsureIterable(source), emptySeq);
}

export default /*#__PURE__*/ asyncWrapWithResultIterable(asyncJoin);
