/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$join.d.ts#1643907550750
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncJoin<T>(source: AsyncWrappable<AsyncWrappable<T>>): AsyncIterableIterator<T>;

export { asyncJoin };
