/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$join.js#1643837503081
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { wrapWithIterableIterator, ensureIterable } from '../../internal/iterable.js';
import { __joinWithSeq } from '../$join-with-seq/join-with-seq.js';

const emptySeq = [];

export function __join(source) {
  return __joinWithSeq(ensureIterable(source), emptySeq);
}

export const join = /*#__PURE__*/ wrapWithIterableIterator(__join);
