/* @macrome
 * @generated-from ./$consume.test.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncConsume } from '../../..';

describe('asyncConsume', () => {
  it('consumes an iterable', async () => {
    const arr: Array<number> = [];
    await asyncConsume(
      (function*() {
        arr.push(1);
        yield;
        arr.push(2);
        yield;
        arr.push(3);
      })(),
    );
    expect(arr).toEqual([1, 2, 3]);
  });
});
