/**
 * @generated-from ./async-to-array.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

/* eslint-disable no-unused-vars,import/no-duplicates,no-constant-condition */

import { asyncToArray } from '../../..';
import { asyncWrap } from '../../../test/async-helpers';

describe('asyncToArray', () => {
  it('turns an iterable into an array', async () => {
    expect(await asyncToArray(asyncWrap([1, 2, 3]))).toEqual([1, 2, 3]);
  });
});
