/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$map.test.ts#1643907550751
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncMap } from 'iter-tools-es';
import { asyncWrap, asyncUnwrap } from '../../../test/async-helpers.js';

describe('asyncMap', () => {
  describe('when source is empty', () => {
    it('yields no values', async () => {
      const func = (value: any) => value * 2;
      expect(await asyncUnwrap(asyncMap(func, null))).toEqual([]);
      expect(await asyncUnwrap(asyncMap(func, undefined))).toEqual([]);
      expect(await asyncUnwrap(asyncMap(func, asyncWrap([])))).toEqual([]);
    });
  });

  describe('when source has values', () => {
    it('returns func(value, i) for each value in source', async () => {
      expect(await asyncUnwrap(asyncMap((value, i) => value + i, asyncWrap([1, 2, 3])))).toEqual([
        1,
        3,
        5,
      ]);
    });
  });

  it('can take an async func', async () => {
    expect(await asyncUnwrap(asyncMap(async (value) => value * 2, asyncWrap([1, 2, 3])))).toEqual([
      2,
      4,
      6,
    ]);
  });
});
