/**
 * @generated-from ./$starts-with-any.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncInputIterable } from '../../internal/async-iterable';
import { InputIterable as SyncInputIterable } from '../../internal/iterable';
declare function asyncStartsWithAny(
  values: SyncInputIterable<any>,
): (iterable: AsyncInputIterable<any>) => Promise<boolean>;
declare function asyncStartsWithAny(
  values: SyncInputIterable<any>,
  iterable: AsyncInputIterable<any>,
): Promise<boolean>;
export default asyncStartsWithAny;
