/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$wrap.js#1643837503117
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncWrapWithIterableIterator } from '../../internal/async-iterable.js';
import { asyncNullableWrap as __asyncWrap } from '../../internal/async-wrap.js';

export { __asyncWrap };

export const asyncWrap = /*#__PURE__*/ asyncWrapWithIterableIterator(__asyncWrap);
