/* @macrome
 * @generated-from ./methods/$append/append.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import append from './methods/$append/append';

export default append;
