/**
 * @generated-from ./methods/array-first/array-first.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import arrayFirst from './methods/array-first/array-first';

export default arrayFirst;
