/**
 * @generated-from ./methods/$tap/async-tap.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import asyncTap from './methods/$tap/async-tap';

export default asyncTap;
