/**
 * @generated-from ./$concat.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { asyncEnsureIterable } from './internal/async-iterable'

async function * asyncConcat (...arrayOfIter) {
  for (const iterable of arrayOfIter) {
    yield * asyncEnsureIterable(iterable)
  }
}

export default asyncConcat
