/**
 * @generated-from ./$map.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import {
  AsyncInputIterable,
  AsyncIterableIterator,
  AsyncMaybePromise,
} from './internal/async-iterable';
declare function asyncMap<O, T = any>(
  func: (item: T) => AsyncMaybePromise<O>,
): (iterable: AsyncInputIterable<T>) => AsyncIterableIterator<O>;
declare function asyncMap<O, T = any>(
  func: (item: T) => AsyncMaybePromise<O>,
  iterable: AsyncInputIterable<T>,
): AsyncIterableIterator<O>;
export default asyncMap;
