/* @macrome
 * @generated-from ./methods/$enumerate/async-enumerate.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import asyncEnumerate from './methods/$enumerate/async-enumerate';

export default asyncEnumerate;
