/* @macrome
 * @generated-from ./methods/$leading-window/async-leading-window.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import asyncLeadingWindow from './methods/$leading-window/async-leading-window';

export default asyncLeadingWindow;
