/* @macrome
 * @generated-from ./methods/$map/async-map.mjs
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import asyncMap from './methods/$map/async-map';

export default asyncMap;
