/**
 * @generated-from ./$multi-partition.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { GeneratorIterator } from './internal/iterable';
import {
  AsyncIterableLike,
  AsyncIterableIterator,
  AsyncMaybePromise,
} from './internal/async-iterable';
declare function asyncMultiPartition<T = any>(
  func: (item: T) => AsyncMaybePromise<number>,
  iterable: AsyncIterableLike<T>,
): GeneratorIterator<AsyncIterableIterator<T>>;
declare function asyncMultiPartition<T = any>(
  func: (item: T) => AsyncMaybePromise<number>,
): (iterable: AsyncIterableLike<T>) => GeneratorIterator<AsyncIterableIterator<T>>;
export default asyncMultiPartition;
