/**
 * @generated-from ./$interpose.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncIterableLike, AsyncIterableIterator } from './internal/async-iterable';
declare function asyncInterpose<I>(
  interposeItem: I,
): <T = any>(iterable: AsyncIterableLike<T>) => AsyncIterableIterator<T | I>;
declare function asyncInterpose<I, T = any>(
  interposeItem: I,
  iterable: AsyncIterableLike<T>,
): AsyncIterableIterator<T | I>;
export default asyncInterpose;
