/**
 * @generated-from ./methods/$starts-with-any-seq/async-starts-with-any-seq.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import asyncStartsWithAnySeq from './methods/$starts-with-any-seq/async-starts-with-any-seq';

export default asyncStartsWithAnySeq;
