/* @macrome
 * @generated-from ./methods/$join-as-string-with/async-join-as-string-with.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import asyncJoinAsStringWith from './methods/$join-as-string-with/async-join-as-string-with';

export default asyncJoinAsStringWith;
