/**
 * @generated-from ./methods/$group/async-group.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import asyncGroup from './methods/$group/async-group';

export default asyncGroup;
