/**
 * @generated-from ./methods/call/call.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import call from './methods/call/call';

export default call;
