/**
 * @generated-from ./methods/combinations-with-replacement/combinations-with-replacement.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import combinationsWithReplacement from './methods/combinations-with-replacement/combinations-with-replacement';

export default combinationsWithReplacement;
