/**
 * @generated-from ./$compress.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import compose from './compose';
import zip from './zip';
import filter from './filter';
import map from './map';

function compress(iterable, compress) {
  return compose(
    map(entry => entry[0]),
    filter(entry => entry[1]),
  )(zip(iterable, compress));
}

export { compress as default };
