/* @macrome
 * @generated-from ./methods/$flat-map/flat-map.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import flatMap from './methods/$flat-map/flat-map';

export default flatMap;
