/* @macrome
 * @generated-from ./methods/$is-empty/is-empty.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import isEmpty from './methods/$is-empty/is-empty';

export default isEmpty;
