/* @macrome
 * @generated-from ./methods/$is-sorted/is-sorted.mjs
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import isSorted from './methods/$is-sorted/is-sorted';

export default isSorted;
