/* @macrome
 * @generated-from ./methods/null-or-async/null-or-async.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import nullOrAsync from './methods/null-or-async/null-or-async';

export default nullOrAsync;
