/* @macrome
 * @generated-from ./methods/object-from-async/object-from-async.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import objectFromAsync from './methods/object-from-async/object-from-async';

export default objectFromAsync;
