/* @macrome
 * @generated-from ./methods/$reduce/reduce.mjs
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import reduce from './methods/$reduce/reduce';

export default reduce;
