/**
 * @generated-from ./methods/regexp-split/regexp-split.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import regexpSplit from './methods/regexp-split/regexp-split';

export default regexpSplit;
