/**
 * @generated-from ./methods/repeat-times/repeat-times.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import repeatTimes from './methods/repeat-times/repeat-times';

export default repeatTimes;
