/* @macrome
 * @generated-from ./methods/$split-on-subseq/split-on-subseq.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import splitOnSubseq from './methods/$split-on-subseq/split-on-subseq';

export default splitOnSubseq;
