/**
 * @generated-from ./methods/$split-on-seq/split-on-seq.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import splitOnSeq from './methods/$split-on-seq/split-on-seq';

export default splitOnSeq;
