/**
 * @generated-from ./methods/$starts-with/starts-with.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import startsWith from './methods/$starts-with/starts-with';

export default startsWith;
