/**
 * @generated-from ./methods/$take-sorted/take-sorted.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import takeSorted from './methods/$take-sorted/take-sorted';

export default takeSorted;
