/**
 * @generated-from ./methods/$to-object/to-object.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import toObject from './methods/$to-object/to-object';

export default toObject;
