/* @macrome
 * @generated-from ./methods/when/when.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import when from './methods/when/when';

export default when;
