/**
 * @generated-from ./methods/wrap-entries/wrap-entries.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import wrapEntries from './methods/wrap-entries/wrap-entries';

export default wrapEntries;
