/**
 * @generated-from ./methods/$zip-all/zip-all.mjs
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import zipAll from './methods/$zip-all/zip-all';

export default zipAll;
