/* @macrome
 * @generated-from ./methods/$zip/zip.d.ts
 * @generated-by generate/generators/methods-links/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import zip from './methods/$zip/zip';

export default zip;
