/**
 * @generated-from ./$concat.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import {
  asyncWrapWithIterableIterator,
  asyncEnsureIterable,
} from '../../internal/async-iterable.js';

export async function* __asyncConcat(...sources) {
  for (const iterable of sources) {
    yield* asyncEnsureIterable(iterable);
  }
}

export const asyncConcat = /*#__PURE__*/ asyncWrapWithIterableIterator(__asyncConcat);
