/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$concat.js#1643907550720
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import {
  _awaitAsyncGenerator as _awaitAsyncGenerator2,
  _wrapAsyncGenerator,
  _awaitAsyncGenerator,
  _asyncIterator,
  _asyncGeneratorDelegate,
} from '../../internal/asyncish.js';

import {
  asyncWrapWithIterableIterator,
  asyncEnsureIterable,
} from '../../internal/async-iterable.js';

export function __asyncConcat() {
  return _$__concat.apply(this, arguments);
}

function _$__concat() {
  _$__concat = _wrapAsyncGenerator(function* (...sources) {
    for (const iterable of sources) {
      yield* _asyncGeneratorDelegate(
        _asyncIterator(asyncEnsureIterable(iterable)),
        _awaitAsyncGenerator,
      );
    }
  });

  return _$__concat.apply(this, arguments);
}

export const asyncConcat = /*#__PURE__*/ asyncWrapWithIterableIterator(__asyncConcat);
