/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$concat.d.ts#1643837503048
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function concat<T>(...sources: Array<Wrappable<T>>): IterableIterator<T>;

export { concat };
