/**
 * @generated-from ./$take-last-or.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';

export function __takeLastOr(iterable, whenEmpty) {
  let _value = whenEmpty;

  for (const value of iterable) {
    _value = value;
  }

  return _value;
}

export const takeLastOr = /*#__PURE__*/ iterableCurry(__takeLastOr, {
  reduces: true,
});
