/* @macrome
 * @generated-from ./$split-on-any.d.ts
 * @generated-by generate/generators/$types/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { SourceIterable as SyncSourceIterable } from '../../types/iterable';
import { SourceIterable, ResultIterable } from '../../types/iterable';

declare function splitOnAny(
  separatorValues: SyncSourceIterable<string>,
): (source: string) => ResultIterable<string>;

declare function splitOnAny(
  separatorValues: SyncSourceIterable<any>,
): <T>(source: SourceIterable<T>) => ResultIterable<ResultIterable<T>>;

declare function splitOnAny(
  separatorValues: SyncSourceIterable<string>,
  source: string,
): ResultIterable<string>;

declare function splitOnAny<T>(
  separatorValues: SyncSourceIterable<any>,
  source: SourceIterable<T>,
): ResultIterable<ResultIterable<T>>;

export default splitOnAny;
