/* @macrome
 * @generated-from ./$concat.js
 * @generated-by generate/generators/$methods/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncWrapWithMethodIterable, asyncEnsureIterable } from '../../internal/async-iterable';

export async function* asyncConcat(...sources) {
  for (const iterable of sources) {
    yield* asyncEnsureIterable(iterable);
  }
}

export default asyncWrapWithMethodIterable(asyncConcat);
