/**
 * @generated-from ./$enumerate.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncEnumerate<T>(iterable: AsyncWrappable<T>): AsyncIterableIterator<[number, T]>;

declare function asyncEnumerate<T>(
  firstIdx: number,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<[number, T]>;

declare function asyncEnumerate(
  firstIdx: number,
): <T>(source: AsyncWrappable<T>) => AsyncIterableIterator<[number, T]>;

export { asyncEnumerate };
