/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$split-groups.spec.ts#1643837503091
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import assert from 'static-type-assert';
import { splitGroups } from 'iter-tools-es';
import { Iterable, IterableIterator } from '../../../types/iterable';

declare const Ø: never;

assert<IterableIterator<[string, IterableIterator<number>]>>(
  splitGroups(Ø as (x: number) => string)(Ø as Iterable<number>),
);

assert<IterableIterator<[string, IterableIterator<number>]>>(
  splitGroups(Ø as (x: number) => string, Ø as Iterable<number>),
);

assert<IterableIterator<[string, IterableIterator<string>]>>(splitGroups(Ø as string));

assert<IterableIterator<[number, IterableIterator<number>]>>(splitGroups(Ø as Iterable<number>));
