/**
 * @generated-from ./$trailing-window.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable';
import { CircularBuffer, ReadOnlyCircularBuffer } from '../../internal/circular-buffer';

import { validateWindowArgs } from './internal/validate-window-args';

export function* trailingWindow(source, size, { filler } = {}) {
  const buffer = new CircularBuffer(size);
  const bufferReadProxy = new ReadOnlyCircularBuffer(buffer);

  buffer.fill(filler);

  for (const item of source) {
    buffer.push(item);
    yield bufferReadProxy;
  }
}

export default iterableCurry(trailingWindow, {
  minArgs: 1,
  maxArgs: 2,
  optionalArgsAtEnd: true,
  validateArgs: validateWindowArgs('trailingWindow'),
});
