/**
 * @generated-from ./cycle.test.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

/* eslint-disable no-unused-vars,import/no-duplicates,no-constant-condition */

import { cycle, slice } from '../../..';
import { wrap, unwrap } from '../../../test/helpers';

describe('cycle', () => {
  describe('when source is empty', () => {
    it('yields no items', () => {
      expect(unwrap(cycle(null))).toEqual([]);
      expect(unwrap(cycle(undefined))).toEqual([]);
      expect(unwrap(cycle([]))).toEqual([]);
    });
  });

  describe('when source has values', () => {
    it('yields those values repeatedly forever', () => {
      expect(unwrap(slice(0, 7, cycle(wrap([1, 2, 3]))))).toEqual([1, 2, 3, 1, 2, 3, 1]);
    });
  });
});
