/**
 * @generated-from ./$flat-map.d.ts
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncFlatMap<O, T>(
  func: (value: T, i: number) => AsyncWrappable<O> | Promise<AsyncWrappable<O>>,
): (source: AsyncWrappable<T>) => AsyncIterableIterator<O>;

declare function asyncFlatMap<O, T>(
  func: (value: T, i: number) => AsyncWrappable<O> | Promise<AsyncWrappable<O>>,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<O>;

export { asyncFlatMap };
