/**
 * @generated-from ./$flat-map.js
 * This file is autogenerated from a template. Please do not edit it directly.
 * To rebuild it from its template use the command
 * > npm run generate
 * More information can be found in CONTRIBUTING.md
 */

import { iterableCurry } from '../../internal/iterable.js';
import { map } from '../$map/map.js';

export function* flatMap(source, func) {
  for (const item of map(source, func)) {
    yield* item;
  }
}

export default /*#__PURE__*/ iterableCurry(flatMap);
