/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$flat-map.js#1643907550734
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { iterableCurry } from '../../internal/iterable.js';
import { __map } from '../$map/map.js';

export function* __flatMap(source, func) {
  for (const value of __map(source, func)) {
    yield* value;
  }
}

export const flatMap = /*#__PURE__*/ iterableCurry(__flatMap);
