/* @macrome
 * @generated-from ./async-find.test.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncFind } from '../../..';

describe('asyncFind', () => {
  it('returns found item', async () => {
    expect(await asyncFind(item => item === 5, [1, 2, 3, 4, 5, 6])).toBe(5);
  });

  it('returns undefined if no item found', async () => {
    expect(await asyncFind(_ => false, [1, 2, 3, 4, 5, 6])).toBe(undefined);
  });

  it('returns undefined when iterable is empty', async () => {
    expect(await asyncFind((item: never) => item, null)).toBe(undefined);
  });

  it('returns found item (using a promise)', async () => {
    expect(await asyncFind(async item => item === 5, [1, 2, 3, 4, 5, 6])).toBe(5);
  });
});
