/* @macrome
 * @generated-from ./$find.spec.ts
 * @generated-by generate/generators/$types/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import assert from 'static-type-assert';
import { Iterable } from '../../../types/iterable';
import { find } from '../../..';

declare const Ø: never;

assert<number | undefined>(find(Ø as (item: number) => any, Ø as Iterable<number>));

assert<2 | undefined>(find(Ø as (item: number) => item is 2, Ø as Iterable<number>));
