/* @macrome
 * @generated-from ./$split.d.ts
 * @generated-by generate/generators/$types/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { ResultIterable as SyncResultIterable } from '../../types/iterable';
import { AsyncSourceIterable, AsyncResultIterable } from '../../types/async-iterable';

declare function asyncSplit<T>(
  source: AsyncSourceIterable<T>,
): AsyncResultIterable<SyncResultIterable<T>>;

declare function asyncSplit(source: string): string;

export default asyncSplit;
