/* @macrome
 * @generated-from ./$split.d.ts
 * @generated-by generate/generators/$types/index.js
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { ResultIterable as SyncResultIterable } from '../../types/iterable';
import { SourceIterable, ResultIterable } from '../../types/iterable';

declare function split<T>(source: SourceIterable<T>): ResultIterable<SyncResultIterable<T>>;

declare function split(source: string): string;

export default split;
